version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
      - ./config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_NAME: udagram
      POSTGRES_HOST_AUTH_METHOD: "trust"


  pgadmin:
    image: dpage/pgadmin4
    ports:
    - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: roazaid@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmind:/var/lib/pgadmin

volumes:
  postgres:
  pgadmind:
